require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VerificationOrdersController do

  # This should return the minimal set of attributes required to create a valid
  # VerificationOrder. As you add validations to VerificationOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "users_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VerificationOrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all verification_orders as @verification_orders" do
      verification_order = VerificationOrder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:verification_orders).should eq([verification_order])
    end
  end

  describe "GET show" do
    it "assigns the requested verification_order as @verification_order" do
      verification_order = VerificationOrder.create! valid_attributes
      get :show, {:id => verification_order.to_param}, valid_session
      assigns(:verification_order).should eq(verification_order)
    end
  end

  describe "GET new" do
    it "assigns a new verification_order as @verification_order" do
      get :new, {}, valid_session
      assigns(:verification_order).should be_a_new(VerificationOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested verification_order as @verification_order" do
      verification_order = VerificationOrder.create! valid_attributes
      get :edit, {:id => verification_order.to_param}, valid_session
      assigns(:verification_order).should eq(verification_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VerificationOrder" do
        expect {
          post :create, {:verification_order => valid_attributes}, valid_session
        }.to change(VerificationOrder, :count).by(1)
      end

      it "assigns a newly created verification_order as @verification_order" do
        post :create, {:verification_order => valid_attributes}, valid_session
        assigns(:verification_order).should be_a(VerificationOrder)
        assigns(:verification_order).should be_persisted
      end

      it "redirects to the created verification_order" do
        post :create, {:verification_order => valid_attributes}, valid_session
        response.should redirect_to(VerificationOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved verification_order as @verification_order" do
        # Trigger the behavior that occurs when invalid params are submitted
        VerificationOrder.any_instance.stub(:save).and_return(false)
        post :create, {:verification_order => { "users_id" => "invalid value" }}, valid_session
        assigns(:verification_order).should be_a_new(VerificationOrder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VerificationOrder.any_instance.stub(:save).and_return(false)
        post :create, {:verification_order => { "users_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested verification_order" do
        verification_order = VerificationOrder.create! valid_attributes
        # Assuming there are no other verification_orders in the database, this
        # specifies that the VerificationOrder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VerificationOrder.any_instance.should_receive(:update).with({ "users_id" => "1" })
        put :update, {:id => verification_order.to_param, :verification_order => { "users_id" => "1" }}, valid_session
      end

      it "assigns the requested verification_order as @verification_order" do
        verification_order = VerificationOrder.create! valid_attributes
        put :update, {:id => verification_order.to_param, :verification_order => valid_attributes}, valid_session
        assigns(:verification_order).should eq(verification_order)
      end

      it "redirects to the verification_order" do
        verification_order = VerificationOrder.create! valid_attributes
        put :update, {:id => verification_order.to_param, :verification_order => valid_attributes}, valid_session
        response.should redirect_to(verification_order)
      end
    end

    describe "with invalid params" do
      it "assigns the verification_order as @verification_order" do
        verification_order = VerificationOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VerificationOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => verification_order.to_param, :verification_order => { "users_id" => "invalid value" }}, valid_session
        assigns(:verification_order).should eq(verification_order)
      end

      it "re-renders the 'edit' template" do
        verification_order = VerificationOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VerificationOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => verification_order.to_param, :verification_order => { "users_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested verification_order" do
      verification_order = VerificationOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => verification_order.to_param}, valid_session
      }.to change(VerificationOrder, :count).by(-1)
    end

    it "redirects to the verification_orders list" do
      verification_order = VerificationOrder.create! valid_attributes
      delete :destroy, {:id => verification_order.to_param}, valid_session
      response.should redirect_to(verification_orders_url)
    end
  end

end
